name: jekyll-build-optional-deploy-gh-pages
description: 'A Configurable jekyll repo builder.  Change what dir it builds; where and if it deploys.'
branding: 
  icon: 'sliders'
  color: 'purple'
runs:
  using: 'docker'
  image: 'Dockerfile'